# Generated by Django 3.2.6 on 2021-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_deleted',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
